source "https://rubygems.org"

gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
end

# Required on Ruby 3.4+, where these moved out of the standard library.
gem "csv"
gem "base64"
gem "bigdecimal"
